//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public Nullable<long> Project_Id { get; set; }

        public override string ToString()
        {
            return $"{FirstName} {LastName}({Id})";
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> ProjectEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> ProjectLeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> ProjectWoker { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.ProjectEmployee = new HashSet<Project>();
            this.ProjectLeader = new HashSet<Project>();
            this.ProjectWoker = new HashSet<Project>();

            FirstName = string.Empty;
            LastName = string.Empty;
            MiddleName = string.Empty;
            Email = string.Empty;
        }
        public Worker(string firstName, string lastName, string middleName, string email) : this()
        {
            FirstName = firstName;
            LastName = lastName;
            MiddleName = middleName;
            Email = email;
        }

        public Worker Update(Worker worker)
        {
            FirstName = worker.FirstName;
            LastName = worker.LastName;
            MiddleName = worker.MiddleName;
            Email = worker.Email;

            return this;
        }
    }
}
